name:                bblisp
version:             0.1.0.0
github:              "kfgavinlam/bblisp"
license:             BSD3
author:              "Gavin Lam"
maintainer:          "me@gavin.hk"
copyright:           "2018 Gavin Lam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kfgavinlam/bblisp#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools:
  - alex >= 3.2 && < 3.3
  dependencies:
  - array >= 0.5 && < 0.6
  - containers >= 0.6 && < 0.7
  - scientific >= 0.3 && < 0.4

executables:
  bblisp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bblisp

tests:
  bblisp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bblisp
    - hspec >= 2.6 && < 2.7
